from typing import Protocol, Awaitable
from string import Template

class VexaInterface(Protocol):
    user_name: str
    ai_name: str
    user_description: str
    system_prompt: str
    prompt_template: str

    def update_description(self, text: str) -> None: ...
    def update_statusbar(self, text: str) -> None: ...
    def clear_conversation(self) -> None: ...
    def exit_app(self) -> None: ...
    def handle_ai_prompt(self, prompt: str) -> None: ...
